Repository Meetfolio-Project-CodeZ-Team/Backend, pull requests merged in 2024-05, with the labels that each got.

#98 :fire: Fix: GPT Feedback 데이터 저장에 따른 데이터 자료형 변환
  src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
Labels: :bug: BugFix

#100 Feat: 카카오페이 프론트 연동 API 구현
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/KakaoPayRequest.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentRequest.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentCommandService.java
Labels: :sparkles: Feature

#101 Feat: 내가 댓글 단 게시글 목록 조회 -> 내 댓글 목록 조회 API 변경
  src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java
  src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
Labels: :sparkles: Feature

#103 Feat: 타 사용자 포트폴리오 조회 API
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/board/service/BoardCommandService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java
  src/main/java/com/codez4/meetfolio/domain/experience/dto/ExperienceResponse.java
  src/main/java/com/codez4/meetfolio/domain/experience/service/ExperienceQueryService.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
Labels: :sparkles: Feature

#107 Feat: 관리자 AI 모델 관리 API 구현
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/model/Model.java
  src/main/java/com/codez4/meetfolio/domain/model/repository/ModelRepository.java
  src/main/java/com/codez4/meetfolio/domain/model/service/ModelQueryService.java
  src/main/java/com/codez4/meetfolio/global/response/code/status/ErrorStatus.java
  src/main/java/com/codez4/meetfolio/global/utils/RedisUtil.java
Labels: :sparkles: Feature

#109 Main Merge: Merge 20차
  src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java
Labels: :twisted_rightwards_arrows: PullRequest

#110 Feat: 카카오 페이 tid 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
Labels: :sparkles: Feature

#112 Hotfix : 월별 결제 내역 API 버그 수정
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
Labels: :bug: BugFix

#116 Refactor: 카카오 페이 승인 정보 등록 로직 수정
  src/main/java/com/codez4/meetfolio/domain/payment/Payment.java
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentRequest.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
Labels: :recycle: Refactor

#115 Fix: 모델 정보 조회 response 스펙 수정
  src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java
Labels: :bug: BugFix

#118 Feat: AI 솔루션 만족도 저장 API 구현
  src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisCommandService.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackCommandService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
Labels: :sparkles: Feature

#119 Merge: Main Merge 23차
  src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java
  src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisCommandService.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackCommandService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
  src/main/java/com/codez4/meetfolio/domain/payment/Payment.java
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentRequest.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
Labels: :twisted_rightwards_arrows: PullRequest

#128 Fix: 관리자 게시물 목록 조회 오류 수정
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
Labels: :bug: BugFix

#129 Merge : Main Merge 26차
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/Comment.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
Labels: :twisted_rightwards_arrows: PullRequest

#133 Fix: 관리자 결제 내역 조회 오류 수정
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
Labels: :bug: BugFix

#134 Merge : Main Merge 27차
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest

#135 Feat: 좋아요 갯수 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/like/controller/LikeController.java
  src/main/java/com/codez4/meetfolio/domain/like/dto/LikeResponse.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeCommandService.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeQueryService.java
Labels: :sparkles: Feature

#138 Hotfix: 관리자 회원 목록 조회 시 탈퇴한 회원 제거 로직 추가
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
  src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
Labels: :bug: BugFix

#137 Merge: Main Merge 28차
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/like/controller/LikeController.java
  src/main/java/com/codez4/meetfolio/domain/like/dto/LikeResponse.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeCommandService.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
  src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
Labels: :twisted_rightwards_arrows: PullRequest

#141 Hotfix : 모델 상세 정보 조회/ 탈퇴 회원 제거 로직
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/ModelResponse.java
  src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
Labels: :bug: BugFix

#144 Hotfix: 사용자 개인정보 수정 로직 수정
  src/main/java/com/codez4/meetfolio/domain/member/Member.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberCommandService.java
Labels: :bug: BugFix

#149 Hotfix: 댓글 수정 request dto 추가
  src/main/java/com/codez4/meetfolio/domain/comment/controller/CommentController.java
  src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentRequest.java
Labels: :bug: BugFix

#150 Merge: Main Merge 32차
  src/main/java/com/codez4/meetfolio/domain/comment/controller/CommentController.java
  src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentRequest.java
Labels: :twisted_rightwards_arrows: PullRequest

#153 Feat: 프로필 이모지 설정 로직 구현
  src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java
  src/main/java/com/codez4/meetfolio/domain/enums/ProfileEmoji.java
  src/main/java/com/codez4/meetfolio/domain/member/Member.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
Labels: :sparkles: Feature

#155 Refactor : 모델 삭제 시 soft delete 구현
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/enums/VersionStatus.java
  src/main/java/com/codez4/meetfolio/domain/model/Model.java
  src/main/java/com/codez4/meetfolio/domain/model/repository/ModelRepository.java
Labels: :recycle: Refactor

#158 Refactor: 댓글 대댓글 계층 구조 적용
  src/main/java/com/codez4/meetfolio/domain/comment/Comment.java
  src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java
  src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java
Labels: :recycle: Refactor

#159 Merge: Main Merge 34차
  src/main/java/com/codez4/meetfolio/domain/board/repository/EmploymentBoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/GroupBoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/Comment.java
  src/main/java/com/codez4/meetfolio/domain/comment/dto/CommentResponse.java
  src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentCommandService.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/Point.java
  src/main/java/com/codez4/meetfolio/domain/point/controller/PointController.java
  src/main/java/com/codez4/meetfolio/domain/point/dto/PointRequest.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
Labels: :twisted_rightwards_arrows: PullRequest

#166 Feat: 타 사용자 조회 시, 공유한 사용자에게 포인트 전달
  src/main/java/com/codez4/meetfolio/domain/enums/PointType.java
  src/main/java/com/codez4/meetfolio/domain/point/Point.java
  src/main/java/com/codez4/meetfolio/domain/point/dto/PointRequest.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointCommandService.java
Labels: :sparkles: Feature

#170 Refactor: Coverletter 테이블 속성 추가 및 로직 수정
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/dto/PointResponse.java
Labels: :recycle: Refactor

#171 Feat: 포인트 적립 내역 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/controller/PointController.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
Labels: :sparkles: Feature

#172 Merge: Main Merge 37차
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/board/Board.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/controller/PointController.java
  src/main/java/com/codez4/meetfolio/domain/point/dto/PointResponse.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
Labels: :twisted_rightwards_arrows: PullRequest

#174 Chore: 서버 이전으로 인한 url 변경
  src/main/java/com/codez4/meetfolio/domain/payment/dto/KakaoPayRequest.java
  src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
Labels: :construction_worker: Chore, :twisted_rightwards_arrows: PullRequest
