Repository Meetfolio-Project-CodeZ-Team/Backend, pull requests merged in 2024-04, with the labels that each got.

#11 Fix : 엔티티 파일 설계 오류 수정
  src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java
  src/main/java/com/codez4/meetfolio/domain/authentication/Authentication.java
  src/main/java/com/codez4/meetfolio/domain/board/Board.java
  src/main/java/com/codez4/meetfolio/domain/comment/Comment.java
  src/main/java/com/codez4/meetfolio/domain/common/BaseTimeEntity.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java
  src/main/java/com/codez4/meetfolio/domain/enums/Authority.java
  src/main/java/com/codez4/meetfolio/domain/enums/Major.java
  src/main/java/com/codez4/meetfolio/domain/enums/Status.java
  src/main/java/com/codez4/meetfolio/domain/experience/Experience.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
  src/main/java/com/codez4/meetfolio/domain/like/Like.java
  src/main/java/com/codez4/meetfolio/domain/member/Member.java
  src/main/java/com/codez4/meetfolio/domain/model/Model.java
  src/main/java/com/codez4/meetfolio/domain/payment/Payment.java
  src/main/java/com/codez4/meetfolio/domain/point/Point.java
Labels: :bug: BugFix

#15 Remove : JobKeyword 엔티티 삭제
  src/main/java/com/codez4/meetfolio/domain/jobKeyword/JobKeyword.java
  src/main/java/com/codez4/meetfolio/global/annotation/EnumValid.java
  src/main/java/com/codez4/meetfolio/global/annotation/EnumValidator.java
Labels: 🔥 Remove

#20 Feat : 경험 카드 목록, 세부 정보, 추천 경험 카드 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java
  src/main/java/com/codez4/meetfolio/domain/experience/dto/ExperienceResponse.java
  src/main/java/com/codez4/meetfolio/domain/experience/repository/ExperienceRepository.java
  src/main/java/com/codez4/meetfolio/domain/experience/service/ExperienceQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
Labels: :sparkles: Feature

#25 Feat: 자기소개서 세부 정보 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java
  src/main/java/com/codez4/meetfolio/domain/analysis/dto/AnalysisResponse.java
  src/main/java/com/codez4/meetfolio/domain/analysis/repository/AnalysisRepository.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
  src/main/java/com/codez4/meetfolio/domain/feedback/dto/FeedbackResponse.java
  src/main/java/com/codez4/meetfolio/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
  src/main/java/com/codez4/meetfolio/global/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#27 Feat: 자기소개서 작성, 수정, 삭제 API 구현
  src/main/java/com/codez4/meetfolio/domain/analysis/Analysis.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisCommandService.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java
  src/main/java/com/codez4/meetfolio/domain/enums/ShareType.java
  src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java
  src/main/java/com/codez4/meetfolio/domain/experience/dto/ExperienceRequest.java
  src/main/java/com/codez4/meetfolio/domain/experience/service/ExperienceCommandService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackCommandService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
  src/main/java/com/codez4/meetfolio/global/annotation/AuthenticationMemberArgumentResolver.java
  src/main/java/com/codez4/meetfolio/global/config/SecurityConfig.java
  src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codez4/meetfolio/global/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#30 Feat: 관리자 포인트 사용 통계, 결제 내역 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
  src/main/java/com/codez4/meetfolio/domain/payment/Payment.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/Point.java
  src/main/java/com/codez4/meetfolio/domain/point/PointRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/dto/PointResponse.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#37 Feat: Point, Payment 참조 관계 변경
  src/main/java/com/codez4/meetfolio/domain/admin/dto/PaymentAdminResponse.java
  src/main/java/com/codez4/meetfolio/domain/enums/PaymentStatus.java
  src/main/java/com/codez4/meetfolio/domain/payment/Payment.java
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/Point.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
Labels: :sparkles: Feature

#40 Feat: 관리자 대시보드 API 구현
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/PaymentAdminResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/PointAdminResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminService.java
  src/main/java/com/codez4/meetfolio/domain/analysis/repository/AnalysisRepository.java
  src/main/java/com/codez4/meetfolio/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/PaymentResponse.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
Labels: :sparkles: Feature

#42 Feat: 마이페이지 관련 API 구현
  src/main/java/com/codez4/meetfolio/domain/board/GroupBoard.java
  src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java
  src/main/java/com/codez4/meetfolio/domain/board/dto/BoardResponse.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/service/BoardQueryService.java
  src/main/java/com/codez4/meetfolio/domain/comment/Comment.java
  src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/like/repository/LikeRepository.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/Member.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberCommandService.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#43 🔀 Merge : 2차 Main Merge
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/PaymentAdminResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/PointAdminResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminService.java
  src/main/java/com/codez4/meetfolio/domain/analysis/repository/AnalysisRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/GroupBoard.java
  src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java
  src/main/java/com/codez4/meetfolio/domain/board/dto/BoardResponse.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/service/BoardQueryService.java
  src/main/java/com/codez4/meetfolio/domain/comment/Comment.java
  src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/codez4/meetfolio/domain/like/repository/LikeRepository.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/Member.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java
  src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberCommandService.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/repository/PaymentRepository.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/PaymentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/service/PointQueryService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#47 Hotfix: 스웨거 설명 추가
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberRequest.java
Labels: :bug: BugFix, :memo: Docs

#48 Refactor: 게시물 목록 Page 타입에서 Slice타입으로 변환
  src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java
  src/main/java/com/codez4/meetfolio/domain/board/dto/BoardQueryItem.java
  src/main/java/com/codez4/meetfolio/domain/board/dto/BoardResponse.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/EmploymentBoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/GroupBoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/service/BoardQueryService.java
  src/main/java/com/codez4/meetfolio/domain/comment/repository/CommentRepository.java
  src/main/java/com/codez4/meetfolio/domain/comment/service/CommentQueryService.java
  src/main/java/com/codez4/meetfolio/domain/enums/GroupCategory.java
  src/main/java/com/codez4/meetfolio/domain/like/repository/LikeRepository.java
  src/main/java/com/codez4/meetfolio/domain/like/service/LikeQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/global/response/SliceResponse.java
Labels: :sparkles: Feature, :recycle: Refactor

#54 Hotfix: memberinfo 비로그인 사용자 로직 추가
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest

#57 Hotfix: 대시보드 dto 클래스명 수정
  src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java
Labels: :bug: BugFix

#60 Feat: 로그아웃 로직 추가
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/member/service/AuthService.java
  src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codez4/meetfolio/global/response/code/status/ErrorStatus.java
  src/main/java/com/codez4/meetfolio/global/utils/RedisUtil.java
Labels: :sparkles: Feature

#62 Feat: 게시물 검색 및 관리자 게시물 삭제 API 추가
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/BoardResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/dto/DatasetResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/board/controller/BoardController.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/BoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/EmploymentBoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/repository/GroupBoardRepository.java
  src/main/java/com/codez4/meetfolio/domain/board/service/BoardQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java
  src/main/java/com/codez4/meetfolio/domain/enums/BoardType.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/point/Point.java
Labels: :sparkles: Feature

#65 Fix: 경험카드 목록 조회 DTO에 id 값 추가
  src/main/java/com/codez4/meetfolio/domain/experience/dto/ExperienceResponse.java
Labels: :bug: BugFix

#68 Fix: 장문을 받는 cloumn 길이 설정 추가
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
Labels: :bug: BugFix

#69 Merge: Main merge 10차
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/dataset/Dataset.java
  src/main/java/com/codez4/meetfolio/domain/feedback/Feedback.java
Labels: :twisted_rightwards_arrows: PullRequest

#71 Feat: 자기소개서 목록 조회 API 구현
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/test/java/com/codez4/meetfolio/MeetfolioApplicationTests.java
Labels: :sparkles: Feature

#77 Fix: cors config 수정
  src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
  src/main/java/com/codez4/meetfolio/global/config/WebConfig.java
Labels: :bug: BugFix, :construction_worker: Chore

#79 Fix: cors config DNS 주소 수정
  src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
Labels: :bug: BugFix, :construction_worker: Chore

#82 Fix: DNS CORS 마지막 수정
  src/main/java/com/codez4/meetfolio/global/config/CorsConfig.java
Labels: :bug: BugFix

#81 Feat: 자기소개서 및 사용자 정보 API 구현
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
  src/main/java/com/codez4/meetfolio/global/annotation/AuthenticationMemberArgumentResolver.java
  src/main/java/com/codez4/meetfolio/global/config/SecurityConfig.java
  src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#83 Merge: Main Merge 14차
  src/main/java/com/codez4/meetfolio/domain/coverLetter/CoverLetter.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/controller/CoverLetterController.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterRequest.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/dto/CoverLetterResponse.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterCommandService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/experience/controller/ExperienceController.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/MemberController.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
  src/main/java/com/codez4/meetfolio/global/annotation/AuthenticationMemberArgumentResolver.java
  src/main/java/com/codez4/meetfolio/global/config/SecurityConfig.java
  src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java
Labels: :twisted_rightwards_arrows: PullRequest

#84 Fix: 로그아웃 로직 수정
  src/main/java/com/codez4/meetfolio/domain/member/dto/MemberResponse.java
  src/main/java/com/codez4/meetfolio/domain/member/service/AuthService.java
  src/main/java/com/codez4/meetfolio/global/jwt/JwtTokenProvider.java
Labels: :bug: BugFix

#85 Fix: 대시보드 API 로직 수정
  src/main/java/com/codez4/meetfolio/domain/admin/dto/DashboardResponse.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/dataset/repository/DatasetRepository.java
  src/main/java/com/codez4/meetfolio/domain/point/repository/PointRepository.java
Labels: :bug: BugFix

#86 Feat: 관리자 회원 검색 API 구현
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminQueryService.java
  src/main/java/com/codez4/meetfolio/domain/member/repository/MemberRepository.java
Labels: :sparkles: Feature

#88 Refactor: 이메일 인증 코드 테이블 redis로 이관
  src/main/java/com/codez4/meetfolio/domain/emailAuth/EmailAuth.java
  src/main/java/com/codez4/meetfolio/domain/emailAuth/dto/EmailAuthRequest.java
  src/main/java/com/codez4/meetfolio/domain/emailAuth/repository/EmailAuthRepository.java
  src/main/java/com/codez4/meetfolio/domain/emailAuth/service/EmailAuthCommandService.java
  src/main/java/com/codez4/meetfolio/domain/emailAuth/service/EmailAuthQueryService.java
  src/main/java/com/codez4/meetfolio/global/utils/RedisUtil.java
Labels: :recycle: Refactor

#92 Fix: Coverletter API 오류 수정
  src/main/java/com/codez4/meetfolio/domain/analysis/repository/AnalysisRepository.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisCommandService.java
  src/main/java/com/codez4/meetfolio/domain/analysis/service/AnalysisQueryService.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/repository/CoverLetterRepository.java
  src/main/java/com/codez4/meetfolio/domain/coverLetter/service/CoverLetterQueryService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackCommandService.java
  src/main/java/com/codez4/meetfolio/domain/feedback/service/FeedbackQueryService.java
Labels: :bug: BugFix, :recycle: Refactor

#95 Fix: 카카오 페이 승인 API 수정
  src/main/java/com/codez4/meetfolio/domain/payment/controller/PaymentController.java
  src/main/java/com/codez4/meetfolio/domain/payment/dto/KakaoPayRequest.java
  src/main/java/com/codez4/meetfolio/domain/payment/service/KakaoPayService.java
  src/main/java/com/codez4/meetfolio/domain/point/dto/PointRequest.java
  src/main/java/com/codez4/meetfolio/global/config/SecurityConfig.java
  src/main/java/com/codez4/meetfolio/global/jwt/JwtAuthenticationFilter.java
Labels: :bug: BugFix

#94 Feat: 회원 탈퇴 API 구현
  src/main/java/com/codez4/meetfolio/domain/admin/controller/AdminController.java
  src/main/java/com/codez4/meetfolio/domain/admin/service/AdminCommandService.java
  src/main/java/com/codez4/meetfolio/domain/member/Member.java
  src/main/java/com/codez4/meetfolio/domain/member/controller/AuthController.java
  src/main/java/com/codez4/meetfolio/domain/member/service/AuthService.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberCommandService.java
  src/main/java/com/codez4/meetfolio/domain/member/service/MemberQueryService.java
Labels: :sparkles: Feature
